name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod tidy

      - name: Verify formatting
        run: go fmt ./...

      - name: Run tests
        run: go test -v ./...
